### ISSUE TITLE
Improve Indent

### ISSUE THREAD

**Issue by Retmer** [JelteMX/mendix-tree-table#10]
Make realy Ident for Texts longer than the widget width

![image](https://user-images.githubusercontent.com/20553863/69817392-cacab580-11fa-11ea-8feb-2e477715cb50.png)

**Comment by JelteMX** [comment]
This can be fixed by styling your table. I'll see what improvements I can make based on best practices from the [Planner Widget](https://github.com/JelteMX/mendix-planner-widget)
