### ISSUE TITLE
Error on selection

### ISSUE THREAD

**Issue by ajaysdahibhate** [JelteMX/mendix-tree-table#13]
I have followed given steps and able to load the tree table but on selecting one node I am getting this error:
Caused by: java.lang.IllegalArgumentException: requirement failed: Reference 'MyFirstModule.SelectionHelper_View' only accepts ids of type 'MyFirstModule.View' (Id '[MendixIdentifier:: id=3659174697238629 objectType=MyFirstModule.Node entityID=13]' is not allowed).

Any idea about this error?

![DomainModel](https://user-images.githubusercontent.com/50228670/73522523-a2477d80-442e-11ea-855c-e04020382bb2.JPG)
![Helper](https://user-images.githubusercontent.com/50228670/73522524-a2477d80-442e-11ea-8000-b5e199363cea.JPG)

**Comment by JelteMX** [comment]
What Mendix Studio Pro version are you using? I'll see if I can reproduce this. If not I might need a test-project from you to see what is going wrong

**Comment by ajaysdahibhate** [comment]
I am using Mendix Studio Pro 8.3.0. Also tried in 8.4.2.

**Comment by JelteMX** [comment]
Thanks. I will check it out

**Comment by JelteMX** [comment]
I have double checked it in my test-project with both 8.3.0 and 8.4.1, both seems to work fine. I will need to have a look at your project to see if you implemented it correctly. You can also send me a test-project that reproduces this exact issue. You can reach me at jelte.lagendijk [at] mendix.com

**Comment by ajaysdahibhate** [comment]
Thank you Jelte. sending you the test project in which, this issue is occurring.

[TreeTablePractice.zip](https://github.com/JelteMX/mendix-tree-table/files/4146476/TreeTablePractice.zip)

**Comment by JelteMX** [comment]
Thank you, I will have a look at it later today

**Comment by JelteMX** [comment]
Well, that was a short one ;-). You have the following problem:

- On Home_Web you use a Node as the context for you TreeTable
- In the widget you set the reference in the helper to a View
- The widget tries to set the reference to its context, which is a Node, not a View

That's the issue you're having, this is purely an implementation error. What I will do is take this as an example and see if I can improve the errors that the widget produces, as this might have just been overlooked.

**Comment by JelteMX** [comment]
![Screenshot 2020-02-03 09 51 52](https://user-images.githubusercontent.com/14937393/73638510-d4452380-466a-11ea-94da-bd2b3cec7faa.png)

This is the error you will be presented with in the new version of the widget, to make sure you can debug this issue.

**Comment by ajaysdahibhate** [comment]
Thank you for having a look. But I can only see one option while setting the "Reference to context", that is "MyFirstModule.SelectionHelper_View/MyFirstModule.View"
![ReferenceToContext](https://user-images.githubusercontent.com/50228670/73640407-323a3100-4694-11ea-9fcc-f235704b3650.JPG)

How should I resolve this?

**Comment by JelteMX** [comment]
If you would set an extra 1..* association from Node to SelectionHelper that would solve your problem

**Comment by JelteMX** [comment]
SelectionHelper *-->1 Node I mean

**Comment by ajaysdahibhate** [comment]
Thank you Jelte. It's working for me. It would also be helpful if you update the domain model screen shot in tree table documentation.
Thanks for your help!

**Comment by JelteMX** [comment]
No, you are using Node as the context, I am using View as a context, see [here](https://github.com/JelteMX/mendix-tree-table/blob/master/assets/domain-model-example.png). Anyway, good to be able to help. Good luck! :-)

**Comment by ajaysdahibhate** [comment]
Ohh ok.. My bad. Thank you!
