### ISSUE TITLE
Expand on root not takes two click.

### ISSUE THREAD

**Issue by Yogendra0Sharma** [JelteMX/mendix-tree-table#15]
Hi @JelteMX 
I have implemented treetable with load children using Microflow.
When I expand the root now the getchildern Microflow call but tree node unable to expand.for expand need second click on + button and second time getchildern Microflow not called.
Please suggest possible solutions.

**Comment by JelteMX** [comment]
This should be fixed in [2.0.0](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.0.0)
