### ISSUE TITLE
Error on use of inline buttons

### ISSUE THREAD

**Issue by jelleboomsma** [JelteMX/mendix-tree-table#17]
Hi @JelteMX,

we are currently implementing your widget and are encountering an issue when using inline buttons. When used the widget throws the following error in the browser console:

"Objects are not valid as a React child (found: object with keys {title, _hasproblem, text, decimal, date, problem, key, _parent, _mxReferences, children}). If you meant to render a collection of children, use an array instead."

I noticed the same behavior in the test project. Is there any chance this will be fixed in the near future? 

We love the widget by the way! Great job!

Thanks! 
Jelle

**Comment by JelteMX** [comment]
I must have missed something, thanks for bringing this to my attention, I see it [here too](https://reacttreeview-sandbox.mxapps.io/p/inline-buttons). I will prioritize a fix for it, stay tuned

**Comment by JelteMX** [comment]
Fixed in [2.0.3](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.0.3) and released in the App Store. Thanks for reporting!

**Comment by jelleboomsma** [comment]
Awesome! Thanks for fixing this on such a short notice!
