### ISSUE TITLE
TreeTable not populated by nanoflow

### ISSUE THREAD

**Issue by MWBtimeseries** [JelteMX/mendix-tree-table#23]
Hi @JelteMX,

I am trying to use your TreeTable in a PWA, using a nanoflow as a datasource. Unfortunately, the TreeTable is not showing anything. When I use the exact same nanoflow to populate a ListView, I do see the items that I expect. 

Mendix version: 8.9.0
Widget version: v2.0.8

**Comment by JelteMX** [comment]
I will test the standard test-project we have for TreeTable (MX 8.0.0) in 8.9.0 and see what comes up

**Comment by JelteMX** [comment]
Can't seem to find any issue. I downloaded the Test project and opened it in 8.9.0. It still works properly on my end, renders a table.

Can you give me a little bit more specifics? Also, are there any errors produced in your console of your browser?

**Comment by MWBtimeseries** [comment]
Good news is, I don't get any errors. On the other hand, that makes it hard to debug.

I am developing a PWA. In my domain model I have a ItemView object which has multiple Items that has a many-to-many to itself. In addition, I have a SelectionHelper (non-persistent) and a TableColumn entity, although these are not yet being used.

As said, as a data source, I have a NF that simply retrieves the Items that are associated with the ItemView object, which is the page parameter. In addition, I have filled out the columns tab (list definition for two columns for two attributes of Item). Apart from that I have not touched on any of the tabs (Data Children, Helper, Events, etc).

Hope this helps!

**Comment by MWBtimeseries** [comment]
Overnight the problem has vanished... as I am developing a PWA, perhaps there was a browser cache issue? I don't know.

**Comment by JelteMX** [comment]
@MWBtimeseries haha, the magic... Glad you don't have the issue anymore. Not sure if that would be caching. Weird...
