### ISSUE TITLE
Is it possible to add microflow settings to button bar

### ISSUE THREAD

**Issue by besturn20at** [JelteMX/mendix-tree-table#24]
Dear @JelteMX
It is really good component, I am using it to manage files on cloud storage. 
we can call out microflow from button bar. Is it possible to add microflow settings to configure the microflow call?  like following screenshot.  Thanks.
![image](https://user-images.githubusercontent.com/33149475/96237221-9e18bb80-0fcf-11eb-8b5a-6cd19a801abc.png)

**Comment by JelteMX** [comment]
Nope, unfortunately such options do not exist on custom widgets.
