### ISSUE TITLE
Issue 1/3: feeding by XPath via Listen-to-grid

### ISSUE THREAD

**Issue by ivosturm** [JelteMX/mendix-tree-table#30]
When feeding the widget by XPath in a listen-to-grid scenario the widget will break if the user selects a datagrid line, triggering the TreeTable to appear, then deselects and selects the same line again. This issue is part of two other bugs I just shared in a support ticket

**Comment by JelteMX** [comment]
Fixed in [2.3.0](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.3.0)
