### ISSUE TITLE
Issue 2/3: feeding by datasource and Helper entity with refresh

### ISSUE THREAD

**Issue by ivosturm** [JelteMX/mendix-tree-table#31]
When feeding the widget by Datasource and a Helper entity, the widget breaks if a context entity attibute is changed. The full scenario is shared via the support ticket with a demoproject describing the bugs.

**Comment by JelteMX** [comment]
Fixed in [2.3.0](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.3.0)
