### ISSUE TITLE
Issue 3/3: feeding widget via datasource and helper entity doesn't update after second change

### ISSUE THREAD

**Issue by ivosturm** [JelteMX/mendix-tree-table#32]
Related to issue 3/3; if a second change of a value of an attribute of the helper entity is done, the Tree Table isn't refeshing properly. Also added this issue to the demo project uploaded in the support ticket.

**Comment by JelteMX** [comment]
Fixed in [2.3.0](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.3.0)
