### ISSUE TITLE
App crashes due to experimental search functionality.

### ISSUE THREAD

**Issue by jacobdehorn** [JelteMX/mendix-tree-table#33]
My app crashes when I want to use the search function for the tree view widget. I know it is still an experiment, but it is a feature that fits really well in my project. 

I have a project for a factory where you want to select an asset from the factory that needs maintenance. I render the hierarchy of the factory (that goes from machine to screw) in the tree view, but since this can be a lot of clicks for the user I would like to use this search function. 

I configured the search functionality the same as in the demo project. The only difference is that I have more data in my tree view.

**Comment by JelteMX** [comment]
Wrong repository, please add issue to [mendix-tree-view](https://github.com/JelteMX/mendix-tree-view/issues)
